- name: ensure apache is installed
  apt: pkg=apache2 state=installed

- name: copy apache.conf 
  template: src={{ item }}.j2 dest=/etc/apache2/{{ item }} backup=yes
  with_items: 
     - apache2.conf
     - ports.conf 

- name: ensure apache is running
  service: name=apache2 state=started

- name: install module apache 
  command: a2enmod {{item}}  creates="/etc/apache2/mods-enabled/{{item}}.load"
  with_items: mods_list
  notify: Restart Apache
  when: mods_list is defined
