- name: ensure apache is installed
  yum: pkg=httpd state=installed

- name: create {{item}} directory for Apache vhosts
  file: path={{item}} state=directory
  with_items:
     - "/etc/httpd/sites-enabled"
     - "/etc/httpd/sites-available"

- name: copy Apache service configuration template
  template: src="{{item}}.j2" dest="/etc/sysconfig/{{item}}"
  with_items:
     - httpd
  notify: Restart Apache

- name: copy Apache configuration template
  template: src="{{item}}.j2" dest="/etc/httpd/conf/{{item}}"
  with_items:
     - httpd.conf
  notify: Restart Apache

- name: install additionnal modules if any
  yum: pkg={{item}} state=installed
  with_items: module_list
  notify: Restart Apache
  when: module_list is defined
