- name: create user tomcat
  user: name={{ user_tomcat }} createhome="no" state=present 
  when: user_tomcat is defined

- name: create directory for product
  file: path={{ product_dir }}  state=directory 
  when: product_dir is defined

- name: download tomcat
  get_url: url="{{tomcat_tgz_url}}" dest="{{product_dir}}/{{tomcat_tgz}}" mode=0744

- name: untar tomcat
  shell: creates="{{product_dir}}/{{tomcat_dir}}/bin/startup.sh" cd {{product_dir}} && tar -zxvf {{tomcat_tgz}}

- name: create tomcat symlink
  file: src="{{product_dir}}/{{tomcat_dir}}" dest="{{product_dir}}/tomcat" state=link

- name: copy configuration tomcat server.xml
  template: src="server.xml.j2" dest="{{product_dir}}/tomcat/conf/server.xml"

- name: copy configuration tomcat context.xml
  template: src="context.xml.j2" dest="{{product_dir}}/tomcat/conf/context.xml"

- name: copy configuration tomcat catalina.sh
  template: src="catalina.sh.j2" dest="{{product_dir}}/tomcat/bin/catalina.sh"

- name: copy configuration tomcat setclasspath.sh
  template: src="setclasspath.sh.j2" dest="{{product_dir}}/tomcat/bin/setclasspath.sh"

- name: add user privileges on tomcat directory
  file: path={{ product_dir }}  state=directory owner={{ user_tomcat }} group={{ user_tomcat }} mode=764 recurse="yes"
  when: user_tomcat is defined

- name: copy logrotate conf for tomcat
  template: src=logrotate_template.j2 dest='/etc/logrotate.d/tomcat_{{ product_name }}' mode=0644 

- name:  copy init script for tomcat
  template: src=tomcat-init.j2 dest='/etc/init.d/{{ product_name }}' mode=0754 
